NewSpring/Apollos

src/@modules/Header/Header.stories.js
src/@modules/Header/Header.tests.js
src/@modules/Header/__snapshots__/Header.tests.js.snap
src/@modules/Header/index.js

Fixes #39 
TODO: Purposefully not styling the <Text> anymore then text color, as I'm hoping we can swap out the real text component with whatever @burkeshartsis is building.

Style out <Header> component

---

src/@ui/CardWrapper/CardWrapper.stories.js
src/@ui/CardWrapper/CardWrapper.tests.js
src/@ui/CardWrapper/__snapshots__/CardWrapper.tests.js.snap
src/@ui/CardWrapper/index.js
src/@ui/CategoryLabel/CategoryLabel.stories.js
src/@ui/CategoryLabel/CategoryLabel.tests.js
src/@ui/CategoryLabel/__snapshots__/CategoryLabel.tests.js.snap
src/@ui/CategoryLabel/index.js
src/@ui/FeedItemCard/CardImage/CardImage.stories.js
src/@ui/FeedItemCard/CardImage/CardImage.tests.js
src/@ui/FeedItemCard/CardImage/__snapshots__/CardImage.tests.js.snap
src/@ui/FeedItemCard/CardImage/index.js
src/@ui/FeedItemCard/FeedItemCard.stories.js
src/@ui/FeedItemCard/FeedItemCard.tests.js
src/@ui/FeedItemCard/__snapshots__/FeedItemCard.tests.js.snap
src/@ui/FeedItemCard/index.js
src/@ui/FeedItemCard/styles.js
src/@ui/FeedView/__tests__/__snapshots__/FeedView.tests.js.snap

Patches a bunch of stuff that got missed in #133.
- fixes card sizing by removing flex all over and letting the images aspect ratio define card size.
- fixes image sometimes not filling parent due to minHeight on card and flex all over.
- **re-adds missing `isLiked` prop after error during previous merge conflict.**
- fixes stories not using images prop.
- adding missing states to some tests and stories.
- updates CardWrapper to match changes made to feed card down stream and swaps it into feed card as it's card component.

Feed card fixes

---

package.json
src/@ui/ImagePicker/index.js
src/@ui/forms/BillingAddressForm.js
src/@ui/forms/ChangePasswordForm.js
src/@ui/forms/ForgotPasswordForm.js
src/@ui/forms/PaymentConfirmationForm.js
src/@ui/forms/ProfileDetailsForm.js
src/@ui/forms/ResetPasswordForm.js
src/@ui/forms/SavedPaymentReviewForm.js
src/@ui/forms/UploadProfileImageForm/index.js
src/give/ContributionHistory/ContributionHistoryFilter.js
yarn.lock

Fixes eslint `console.log` warnings by pushing previously logged and likely to never be seen errors to Sentry. Also bumps `jest-expo` to latest version.

Fixing eslint console.log warnings

---

src/@ui/HTMLView/index.js
src/@ui/NativeWebRouter/Link.js
src/@ui/WebBrowser/index.web.js
src/give/Checkout/Failure.js
src/give/ContributionHistory/ContributionHistoryList.js
src/give/ScheduleDetails/ScheduleTransactionHistory.js
src/give/Success.js
src/group-finder/GroupSingle.js
src/group-finder/NoResults.js
src/tabs/Discover/Feed.js

Fixes #301 
Uses in-app browser instead of Linking in most places. Created a fallback on web that still uses `Linking`, which will open the link in a new tab.

use in-app browser instead of linking

---

app-config.js

This triggers a feature on ios that should improve loading times. Android has this feature enabled by default.
Also, @IsaacHardy ... could the color issue just have been "fixed", and splash screen backgroundColor can be the same between ios and android now? Not sure...

Performance: Splash Screen

---

src/@ui/Meta/__tests__/__snapshots__/index.js.snap
src/@ui/forms/PaymentConfirmationForm.js
src/@ui/forms/__snapshots__/PaymentConfirmationForm.tests.js.snap

Fixes #416 
Quick tweak to the copy on the contribution form on ios:

Tweak copy for iOS checkout

---

package.json
src/@data/Client/cache.js
src/@data/likes/fragments.js
src/@data/withArticle/index.js
src/@data/withArticles/articlesQuery.js
src/@data/withCachedContent/index.js
src/@data/withNewsStories/newsStoriesQuery.js
src/@data/withNewsStory/index.js
src/@data/withPromotions/promotionsQuery.js
src/@data/withRelatedContent/relatedContentQuery.js
src/@data/withSeriesContent/seriesContentQuery.js
src/@data/withSermon/sermonQuery.js
src/@data/withStories/storiesQuery.js
src/@data/withStory/index.js
src/@ui/ContentView/index.js
src/articles/Single.js
src/news/Single.js
src/series/Sermon.js
src/series/Single.js
src/stories/Single.js
src/studies/Entry/DevotionalTab.js
src/studies/Entry/EntryList.js
src/studies/Entry/index.js
src/studies/Single.js
yarn.lock

This PR does 2 things:
1. Add "cache redirects" for content pieces
2. Improves placeholders in content views
Cache redirects allow us to immediately render content when we're navigating to content that we already have in the cache, but is loaded with a different query. For example, when we navigate from a feed view to an individual item. The individual item is supported by a different query, but we already have some data for that item from the feed view. The net result of this is no more awkward placeholders when navigating between content:

Performance: content placeholders

---

src/SentryContext.js

I believe amplitude is logging a unique user any time we calling `Analytics.identify(null)`, which will skew something like a "Daily new user", "Daily active user", etc.

Only track user if user is logged in

---

android/app/src/main/AndroidManifest.xml

Previously Android app was responding to _any_ url that starts with `newspring.cc/`. This adds in a bunch of restrictions so it only responds to certain paths, so it fixes the issue @FrankGrand discovered where location cards weren't working.
Also, it switches the activity type to `singleInstance`, which _should_ also keep only one instance of the app open ever.

Add restricted paths and use singleInstance for universal linking on android

---

src/@data/withGive/resolvers/mutations.js
src/@data/withGive/resolvers/queries.js
src/@ui/forms/PaymentForm.js
src/@ui/forms/SavedPaymentReviewForm.js
src/give/AddAccount/Complete.js
src/give/AddAccount/Failure.js
src/give/AddAccount/PaymentMethodConfirmation.js
src/give/AddAccount/index.js
src/give/Checkout/Failure.js

So there were two issues to solve.
First, the bad credit card actually _wasn't_ being added, we just weren't properly showing an error message.
Second - and the real bug - we were saving some of the state from saving a credit card so if the user tried again, they wouldn't have to re-enter all their information again. When checking out with a valid credit card, the checkout process was reacting to state that said "Save Credit Card with this name" - except the name was the unsuccessful BAD credit card. So this is fixed by explicitly resetting state when starting a _new_ giving transaction.
I made a few other tweaks though:
- Added "Try again" buttons to both failure state screens on giving and adding payment method
- The same bug (but less severe) existed if you went to gave, added a fake …

Fix dup bad cc bug

---

ios/newspring.xcodeproj/project.pbxproj
ios/newspring/AppDelegate.m

I noticed iOS wasn't getting logged in Fabric, looks like the code I added to xcode didn't make it through the pipe. So, I re-added it.

Fix Fabric on iOS

---

src/@ui/NativeWebRouter/Link.js
src/@utils/analytics/index.js

This adds an analytics event for tracking when users open outside links inside of the app....For example: the live stream. Or a link in an article that opens a webview.

Add outbound link tracking

---

src/@data/withGive/createOrder.js
src/@data/withGive/selectors/getOrderDetails.js

__EDIT:__ I can confirm that this works. To verify on the rock/nmi end, I made a one-time schedule for $1.23 on my account with this PR.
----
This is really just a shot in the dark if it works, but it appears that we do not need to send billing info when creating an order using a saved payment method. So this PR strips out billing info under that scenario.
I posted a couple of orders to apollos-api.newspring.cc:
1. a one-time scheduled payment of today, that had some billing info (like my name and email), but no address. 
2. a one-time scheduled payment of today, that has all billing info stripped out (what this PR does).  
I also checked that this still works okay when saving a payment in the checkout process. Seems to be 👍

Strip Billing info from SavedPayment orders

---

src/give/Dashboard.js

This is a fix for the schedule card (in particular on the giving dashboard) so that if a schedule has multiple funds then the total of those funds appear correctly on the card.
This is a GIF of the before behavior:
This is the "after" of the dashboard with the correct amount showing:

Fix Schedule Card for Multiple Funds

---

src/@data/withGive/createSavePaymentOrder.js
src/@data/withGive/index.js
src/@ui/CardTile/__snapshots__/CardTile.tests.js.snap
src/@ui/forms/SavedPaymentReviewForm.js
src/give/AddAccount/index.js

We recently stopped reseting order state when getting an error in the checkout process so that you could go back and fix any issues. This is causing real orders to be created when adding an account if you previously tried to give but were unsuccessful. This should fix that by clearing order state when you go to add an account.
Essentially just adds a `resetContributions` call to `componentDidMount` on the `AddAccount` component.

Fix: Clear order state when adding an account

---

src/settings/index.js

Fixes #479 
This removes the "Show Onboarding" option from the Setting Menu when viewed on Web.

Created ternary for web view of settings menu

---

src/@ui/SecondaryNav/index.js
src/articles/Single.js
src/group-finder/GroupSingle.js
src/music/Playlist.js
src/news/Single.js
src/series/Sermon.js
src/series/Single.js
src/stories/Single.js
src/studies/Entry/index.js
src/studies/Single.js

Fixes #549 
This attempts to load the secondary nav (think "like and share" nav) only AFTER the content loads. This should fix errors where there is no content to share.

Secondary Nav Loading Fix

---

src/music/Player/FullScreenControls/index.js
src/music/Player/index.js

Fixes #547 by making it respect theming instead of forcing the dark theme all the time. Passed down `isLight` from where the album query was happening so that theme switching would be dynamic.

547 fix music player theming 

---

src/@ui/SecondaryNav/index.js
src/articles/Single.js
src/group-finder/GroupSingle.js
src/music/Playlist.js
src/news/Single.js
src/series/Sermon.js
src/series/Single.js
src/stories/Single.js
src/studies/Entry/index.js
src/studies/Single.js

Fixes #584. This makes sure that the secondary nav on tablets displays horizontally along the bottom on content items while not breaking the secondary nav (like the "X") that displays in places like the sections menu.

Tablet Secondary Nav

---

src/@data/withCheckout/checkoutQuery.js
src/@data/withGive/setBillingAddress.js
src/@data/withUser/index.js
src/@data/withUser/withAddressState.js
src/@data/withUser/withUpdateHomeAddress.js
src/@ui/forms/BillingAddressForm.js
src/@ui/forms/ProfileAddressForm.js

Fixes #440 
I added an input picker for state in the Profile AddressForm. With this change, I created a new data component, withAddressState, within withUser that can be used in BillingAddressForm so that changes made to Profile Address can be used elsewhere and not have to have withCheckout in the ProfileAddressForm.

Normalize Address State field across forms

---

src/group-finder/GroupSingle.js

Remove the share menu on an individual group if it is being displayed on the web
Fixes #606

Fix secondary menu on group finder

---

src/@data/withGivingDashboard/index.js
src/@ui/styled/createStyleSheet.js
src/AppRouter.js
src/give/Dashboard.js
src/give/RestoredCheckout.js
src/give/ScheduleDetails/ScheduleTransactionHistory.js

~Fixes #604~
Implements a few mild performance optimizations:
- Limits dashboard re-rendering a7d6c86
- Fix issue where StyleSheet.create() is called when it doesn't need to be
- Limit RestoredCheckout re-rendering
With #616, I am not sure that this PR is still needed or worth merging. It originally removed the `CardStack` on web, which resulted in a lighter memory footprint and conveniently "fixed" the issue presented in #604. However, it appears that #616 is a better fix...so I reversed the commit I made disabling `CardStack` on web, but I'm still left with the above three potentially "micro" optimizations.

perf optimizations

---

src/@ui/typography/BodyText/index.js
src/assets/fonts/DroidSerif.css

636 Add fontStyle for Safari to display italics

---

src/group-finder/NoResults.js

Fixes #650 by removing the space before the exclamation point that shows up when there are no groups in the group finder search result.

650 Remove space before exclamation point

---

src/@data/withGive/selectors/getOrderDetails.js

Fixed an issue where users scheduled contributions would trigger 24 hours after initial creation instead of set date.

fix-schedule-giving-dates

---

src/AppRouter.js

Changed `/signup` route and hardcoded so that the login route does not render as a modal in this case

Fix Signup Route

---

src/@ui/ImagePicker/index.js

Check for a uri before you try to create an image file
Fixes #591

Fix Image Upload URI

---

.github/PULL_REQUEST_TEMPLATE.md
src/@ui/forms/SavedPaymentReviewForm.js

Fixes [SYS-4478 App does not grab expiration date for credit card payment accounts to send to Rock](https://newspring.atlassian.net/browse/SYS-4478)
This part of a bigger bug, fixed on [NewSpring/Rock](https://github.com/NewSpring/Rock/pull/754)

Fixed Misspelling in Saved Payment Form

---

package.json

This updates the author of our app in the `package.json` to be "NewSpring". 
This is also being used as a test to see if our branches are now correctly up-to-date. I think all this "squashing and merging" (or lack thereof) and then syncing up from `alpha` to `beta` to `master` is messing things up.

Updated the Author

---

.gitignore
package.json
scripts/bump_version.py
src/@ui/forms/PaymentConfirmationForm.js

We can now use `yarn bump [VERSION_NUMBER]` to replace the string in all necessary files and even add the `--ota` flag to automatically publish to Expo.

(SYS-4589) Script to Increment Version Number

---

src/@utils/last4.js

`null` was being passed into `last4()` from somewhere. This actually initializes it to an empty string.
https://sentry.io/newspring-church/apollos/issues/570550606/?query=is%3Aunresolved

(SYS-4594) Initialize Payment String

---

package.json
src/@ui/ContributionsChartHero/index.js
yarn.lock

This makes the picker items on the contribution hero always black. It was ugly in ChromeOS.
**MUST** test in ChromeOS.

(SYS-4590) Fixed Picker on ChromeOS

---

src/@ui/forms/ContributionForm/__snapshots__/ContributionForm.tests.js.snap
src/@ui/forms/ContributionForm/index.js

Fixes [SYS-4574](https://newspring.atlassian.net/secure/RapidBoard.jspa?rapidView=2&projectKey=SYS&modal=detail&selectedIssue=SYS-4574)
This change makes it possible to change a second fund and the fund persist to the review screen.
It still correctly selects a different fund than the original upon initial load.

(SYS-4574) Updated Fund Input to ensure correct fund on review screen

---

.gitignore
android/app/src/main/java/host/exp/exponent/MainActivity.java
android/app/src/main/java/host/exp/exponent/generated/AppConstants.java
appcenter-post-clone.sh

I removed one too many files in a previous PR which I think explains the app crashing, not the short links 🤦‍♂️. So I put that one back.
And then also, It was still looking for files that didn't exist in the build process, so I changed the `post_clone` script to comment out those lines in AppCenter.

Fixes Android AppCenter Builds

---

src/group-finder/GroupCard.js

Fixes [4564](https://newspring.atlassian.net/secure/RapidBoard.jspa?rapidView=2&projectKey=SYS&modal=detail&selectedIssue=SYS-4564)
On Android, `overflow: hidden` doesn't work so we just have to warp the image with a component that has a defined height and width so that it doesn't fill the card.

Adds PaddedView around group card image
