NewSpring/Apollos

package.json, src/@primitives/MediaQuery.js, src/@primitives/MediaQuery/Desktop.js, src/@primitives/MediaQuery/Mobile.js, src/@primitives/MediaQuery/index.js, src/pages/Feed.js
=> 24 media queries

.travis.yml, package.json, yarn.lock
=> use fork for appr

.jestrc.js, package.json, src/@modules/Audio/Audio.tests.js, src/@modules/Audio/__snapshots__/Audio.tests.js.snap, yarn.lock
=> 33-svg-mocks

.gitignore, .scripts/create-app-entrypoint.js, .scripts/create-storybook-entrypoint.js, package.json, src/.storybookWeb/webpack.config.js, src/@modules/Audio/Audio.stories.js
=> Patch storybook web

.travis.yml
=> fix build target selection

.travis.yml
=> Add in config to target master branch on expo deploy

package.json, src/@data/Client.js, src/@data/withMediaPlayer/index.js, src/@data/withMediaPlayer/mediaPlayerQuery.js, src/@data/withMediaPlayer/mutations.js, src/@data/withMediaPlayer/pauseMutation.js, src/@data/withMediaPlayer/playMutation.js, src/@data/withMediaPlayer/queries.js, src/@data/withUser/index.js, src/pages/Feed.js, yarn.lock
I'm not a fan of this but this is how we could put seemingly global things in apollo's state manager. @conrad-vanl @burkeshartsis what do you guys think?
=> 90.1 apollo direct state manipulation

src/@primitives/styled/__snapshots__/styled.tests.js.snap, src/@primitives/styled/index.js, src/@primitives/styled/styled.tests.js
=> add theme to styled

src/@data/withSections/index.js, src/@data/withSections/sectionsQuery.js, src/@modules/SecondaryNav/index.js, src/@modules/TabBar/Layout.js, src/@modules/TileNav/NavItem.js, src/@modules/TileNav/NavItemImage.js, src/@modules/TileNav/index.js, src/@primitives/ActivityIndicator/index.js, src/@primitives/LinearGradient/index.js, src/@primitives/LinearGradient/index.web.js, src/@primitives/ModalView/ModalContainer.js, src/@primitives/ModalView/index.js, src/@primitives/constants.js, src/AppRouter.js, src/tabs/Layout.js, src/tabs/Sections.js
=> sections menu

src/@data/utils/identifyCategory.js, src/@data/withArticles/index.js, src/@data/withDevotionals/index.js, src/@data/withHomeFeed/index.js, src/@data/withNewsStories/index.js, src/@data/withSeries/index.js, src/@data/withStories/index.js, src/@data/withStudies/index.js, src/@primitives/FeedView/__tests__/FeedView.tests.js, src/@primitives/FeedView/__tests__/__snapshots__/FeedView.tests.js.snap, src/@primitives/FeedView/index.js
=> 130 category name

src/@data/utils/identifyCategory.js
=> Hotfix identify category regex

src/@data/Client.js
=> Point to alpha api

src/@ui/ContentView/ContentMedia.js
=> 223 Fix web styles for video

src/@data/withGivingDashboard/givingDashboardQuery.js, src/@ui/AccountCard/index.js, src/@ui/CashAmountIndicator/CashAmountIndicator.stories.js, src/@ui/CashAmountIndicator/CashAmountIndicator.tests.js, src/@ui/CashAmountIndicator/__snapshots__/CashAmountIndicator.tests.js.snap, src/@ui/ContributionsChart/index.js, src/@ui/ContributionsChartCard/index.js, src/@ui/DashboardSubheader/__snapshots__/DashboardSubheader.tests.js.snap, src/@ui/DashboardSubheader/index.js, src/@ui/ExpiringAccountCard/ExpiringAccountCard.tests.js, src/@ui/ExpiringAccountCard/__snapshots__/ExpiringAccountCard.tests.js.snap, src/@ui/ExpiringAccountCard/index.js, src/@ui/ScheduleCard/ScheduleCard.tests.js, src/@ui/ScheduleCard/__snapshots__/ScheduleCard.tests.js.snap, src/@ui/ScheduleCard/index.js, src/@ui/TransactionCard/TransactionCard.tests.js, src/@ui/TransactionCard/__snapshots__/TransactionCard.tests.js.snap, src/@ui/TransactionCard/index.js, src/@ui/forms/ContributionForm/DateInput.tests.js, src/@ui/forms/PaymentForm.js, src/give/Dashboard.js
=> 235 give bug sweep

config/webpack.config.dev.js, config/webpack.config.prod.js, src/.storybook/web/webpack.config.js
=> Fix storybook on web 🎉

src/@ui/ContentView/ContentMedia.js, src/series/Single.js
=> Fix logic error with using `&&` in react-tree

.scripts/ci-deploy.js, app.json, package.json, yarn.lock
=> Upgrade exp

.scripts/ci-deploy.js
=> Use async/await in hopes to fix exp login procedure on travis

.scripts/ci-deploy.js
=> Fix config naming in ci-deploy

src/give/Dashboard.js
=> link new schedule button to correct tab

src/@ui/FeedView/__tests__/__snapshots__/FeedView.tests.js.snap, src/@ui/RelatedContent/__snapshots__/RelatedContent.tests.js.snap, src/@utils/content/getItemImages.js
Fixes #349 as well as an issue affecting current master builds where if a content item had no images, would result in a crashed app.
=> fix empty array error and implement basic aspect ratio sorting

src/@data/withTopics/withToggleTopic.js, src/tabs/Profile/Topics.js
=> Fix topic toggle switches

README.md
Thoughts some of these notes might be relevant / necessary.
=> add apollos-project specific notes

src/AppRouter.js
Fixes #342 
Removed `asModal` from being used in `AppRouter` on these routes.
=> 342 Web: Giving Account Styles

src/@ui/forms/BillingAddressForm.js, src/@ui/forms/ChangePasswordForm.js, src/@ui/forms/ChangePaymentMethodForm.js, src/@ui/forms/EditSavedPaymentMethodForm.js, src/@ui/forms/ForgotPasswordForm.js, src/@ui/forms/LoginForm.js, src/@ui/forms/PaymentForm.js, src/@ui/forms/PersonalDetailsForm.js, src/@ui/forms/ProfileAddressForm.js, src/@ui/forms/ProfileDetailsForm.js, src/@ui/forms/SignUpForm.js
=> Input Validation Text

src/@ui/Meta/__tests__/__snapshots__/index.js.snap, src/@ui/Meta/metadata.js
=> 379 updated meta description

src/@data/withLiveNow/index.js, src/@ui/LiveNowButton/index.js, src/live/index.js
=> 367 Live Redirect

netlify.toml
Update branch names. Capitalized branch names are no bueno.
=> updated branch names

netlify.toml
=> Update master netlify settings

src/give/Now.js
=> 392 help link

netlify.toml, src/@ui/AccountCard/__snapshots__/AccountCard.tests.js.snap, src/@ui/CashAmountIndicator/index.js, src/@ui/Icon/__snapshots__/Icon.tests.js.snap, src/@ui/Icon/icons/Bank.js, src/@ui/SecondaryNav/__snapshots__/SecondaryNav.tests.js.snap, src/@ui/forms/__snapshots__/PaymentConfirmationForm.tests.js.snap, src/@ui/forms/__snapshots__/PaymentForm.tests.js.snap, src/give/Checkout/Failure.js, src/give/Success.js
=> 368 Giving flow style fixes

app-config.js
Using this [issue](https://github.com/expo/expo/issues/826) I updated the background color for iOS.
=> updated background color

src/@ui/forms/ProfileDetailsForm.js, src/@ui/inputs/DateInput/DateInput.tests.js, src/@ui/inputs/DateInput/__snapshots__/DateInput.tests.js.snap
=> 329 profile birthday

.scripts/generate-env-files.js
=> Update env script Token

src/@ui/forms/BillingAddressForm.js
=> 409 Second address field validation fix

src/@ui/forms/ForgotPasswordForm.js
=> Password Reset Form Issues

src/@ui/NativeWebRouter/DeepLinking.js, yarn.lock
Fix an issue where deep linking was being a little too proactive and routing to empty page
Also updates `yarn.lock`
=> Fix DeepLinking white screen on app load

src/@data/withGivingDashboard/index.js, src/@data/withLiveNow/index.js, src/@ui/NativeWebRouter/DeepLinking.js
=> remove polling and fix give flow

src/stories/Single.js
=> fix story heading #389

src/group-finder/AdUnit.js
=> 428 Fix contact us button on group finder

app-config.js
=> update build numbers

src/@ui/OnboardingModal/index.web.js
=> Fixes onboarding to not try to show up on web

src/@data/withGivingDashboard/index.js, src/@ui/NativeWebRouter/DeepLinking.js, src/AppRouter.js, yarn.lock
=> Merge conflicts a b

src/@ui/forms/PaymentForm.js
=> Fixed validation on form load

app-config.js
There is some weird stuff happening with the splash screen lately, and I believe this will fix the issue.
=> fix for splash screen weirdness

src/@ui/forms/PaymentConfirmationForm.js, src/@ui/forms/__snapshots__/PaymentConfirmationForm.tests.js.snap
=> 416-giving-confusion

src/@ui/CardStack/Transitioner.js, src/music/Player/index.js
=> Fix android back button

src/@ui/MediaQuery/MediaQuery.js, src/@ui/forms/ContributionForm/__snapshots__/ContributionForm.tests.js.snap, src/@ui/forms/ContributionForm/index.js, yarn.lock
=> Give as Guest Button

src/@ui/forms/PaymentConfirmationForm.js, src/@ui/forms/__snapshots__/PaymentConfirmationForm.tests.js.snap
=> Fix Change Payment Method Button Link

android/app/src/main/AndroidManifest.xml, ios/newspring/Supporting/Info.plist
=> update fabric keys

src/SentryContext.js
=> Amplitude id fix

android/app/src/main/AndroidManifest.xml, android/app/src/main/java/host/exp/exponent/generated/DetachBuildConstants.java, src/@ui/LiveNowButton/index.js, src/AppRouter.js
I'll try and summarize the universal linking landscape here for the app, but in a nutshell: **TLDR:** This improves the stability of universal link loading on both platforms, and adds configuration so that Android _can_ better respond to universal app links - but a file needs to be uploaded to newspring.cc to fully support.
There was a couple issues this PR tries to fix:
First, when the app opens firebase universal links, the app has to ping `newspring.cc` to know what content to load. This PR adds error handling in-case that request fails. Then, on all universal links, the app has to query heighliner to get content IDs - something like `newspring.cc/devotionals/my-devotional-title` needs to be turned into `/studies/:study_id`. This PR also adds error handling for that query.
Secondly: …
=> Universal linking stability

src/give/ScheduleDetails/ScheduleTransactionHistory.js
Fixes an issue where you could not view the schedule details of a schedule that was already a part of your account.
=> Fixed the schedule history bug thing

ios/newspring/Supporting/LaunchScreen.xib
=> updated splash screen background color

src/@utils/scriptures/__tests__/scriptures.list.js, src/@utils/scriptures/index.js, src/@utils/scriptures/scriptures.list.js, src/studies/Entry/DevotionalTab.js, src/studies/Entry/index.js
=> Scripture link devos

src/@ui/HTMLView/HTMLView.tests.js, src/@ui/HTMLView/__snapshots__/HTMLView.tests.js.snap, src/@ui/HTMLView/index.js
=> Add logic to strip out bad links in HTMLViews

src/@ui/TransactionCard/StatusMessage.js, src/@ui/TransactionCard/index.js
Fixes #548 
It looks like there's a lot of changes, but that just prettify.
=> Fixed TransactionCard Icon and Details to include Pendingsettlement

src/@ui/inputs/DateInput/index.web.js
=> fix dateinput font on web

src/@ui/LiveNowButton/index.js
=> Fixed Watch Live Button

src/AppRouter.js, src/tabs/Layout/index.js
=> Make homepage on web the giving dashboard

src/@ui/WebCompatibleFlatList/index.web.js
=> fix page sizing for content feeds on web

src/@ui/ProgressiveImage/index.js, src/@ui/ThumbnailCard/Thumbnail.js, src/@ui/ThumbnailCard/index.js, src/@ui/UserAvatarView/index.js, src/group-finder/GroupCard.js
=> Fix centering / sizing of web background images

src/@data/Client/errorLink.js
=> 569 improve network sentry errors

.scripts/run-with-settings.js, .scripts/test-script.sh, .travis.yml, package.json, src/@ui/AlbumView/__snapshots__/AlbumView.tests.js.snap, src/@ui/Card/__snapshots__/Card.tests.js.snap, src/@ui/ContentView/__snapshots__/ContentView.tests.js.snap, src/@ui/FeedItemCard/__snapshots__/FeedItemCard.tests.js.snap, src/@ui/FeedView/__tests__/__snapshots__/FeedView.tests.js.snap, src/@ui/ProgressiveImage/__snapshots__/ProgressiveImage.tests.js.snap, src/@ui/RelatedContent/__snapshots__/RelatedContent.tests.js.snap, src/@ui/ThumbnailCard/__snapshots__/ThumbnailCard.tests.js.snap
There's currently an issue where travis builds are succeeding even though there are failing snapshots. This aims to fix that.
=> Fix Travis builds that result in false passes

src/@data/withUser/withLogout.js, src/@utils/reload.js, src/@utils/reload.web.js, src/settings/index.js
=> Fix logout promise fullfillment and logout redirection on web

src/@data/withCheckout/index.js, src/@data/withUser/withAddressState.js, src/@ui/forms/BillingAddressForm.js, src/@ui/forms/BillingAddressForm.tests.js, src/@ui/forms/ProfileAddressForm.js, src/@ui/forms/__snapshots__/BillingAddressForm.tests.js.snap
This splits the state and territory dropdown into separate things based on if you are in the US or Canada.
=> Split State & Territory

src/@ui/CategoryLabel/index.js
=> 353 fix home feed category icons

src/settings/Layout.js, src/settings/Layout.web.js, src/settings/forms.js, src/settings/index.js, src/tabs/Profile/index.web.js
=> Split Layout for Profile Pages

android/app/src/main/java/host/exp/exponent/generated/AppConstants.java, app-config.js, ios/newspring/Supporting/EXShell.plist
=> update build numbers and version

package.json
=> updated package.json version (#600)

src/@data/withGive/selectors/getOrderDetails.js
This fixes us not being able to add a bank account.
=> Fix state to look for stateId

package.json
=> Alpha to Beta

src/group-finder/Results.js, src/tabs/Groups/index.js, src/tabs/Groups/index.web.js
Fixes #592. 
Also fixes the group finder portion of #594.
=> Fix Groupfinder on Tablets

src/@ui/forms/PaymentConfirmationForm.js
Removed sentry from catch handler for paymentform
=> Release v6.0.2 HOTFIX

src/give/ContributionHistory/ContributionHistoryFilter.js
=> Fix for the "All Time" giving history filter not working

src/@ui/Button/Button.js
=> Fix circular reference potential in Sentry breadcrumb logging

android/app/src/main/java/host/exp/exponent/generated/AppConstants.java, app-config.js, ios/newspring/Supporting/EXShell.plist, package.json
=> Update all the versions to 6.0.3

src/give/RestoredCheckout.js
=> 576 iOS Give Confirmation

src/give/Dashboard.js, src/give/Funds/FundCard.js, src/give/GiveRoutes/index.js, src/give/GiveRoutes/index.web.js, src/give/TransactionDetails/index.js, src/give/TransactionDetails/index.web.js
=> Fix Giving Layouts on Tablets

src/@ui/ConnectedImage/index.js
Fixes #637 
See code comment in changes
=> Catch cancellable promise exception

src/@ui/typography/BodyText/index.js, src/@ui/typography/H1/index.js, src/@ui/typography/H2/index.js, src/@ui/typography/H3/index.js, src/@ui/typography/H4/index.js, src/@ui/typography/H5/index.js, src/@ui/typography/H6/index.js, src/@ui/typography/H7/index.js
Fixes #625 on the limited number of [browsers that support font-smoothing](https://caniuse.com/#feat=font-smooth).
=> 625 Antialiased typography on web

src/settings/index.js
=> Fix feedback link on web

src/group-finder/GroupCard.js
=> Fix distances to have two decimal places

src/@ui/RelatedContent/__snapshots__/RelatedContent.tests.js.snap, src/@ui/ThumbnailCard/__snapshots__/ThumbnailCard.tests.js.snap, src/@ui/ThumbnailCard/index.js
=> Fix the capitalization of titles on thumbnail cards

src/group-finder/GroupSingle.js
=> Update group single to use nick name instead of first name

src/@ui/RelatedContent/__snapshots__/RelatedContent.tests.js.snap, src/@ui/TaggedContent/index.js, src/@ui/ThumbnailCard/ThumbnailCard.stories.js, src/@ui/ThumbnailCard/ThumbnailCard.tests.js, src/@ui/ThumbnailCard/__snapshots__/ThumbnailCard.tests.js.snap, src/@ui/ThumbnailCard/index.js
=> Correct font style on Thumbnail Cards

src/group-finder/GroupCard.js
- Using Lodash's `round` because it's safer if what we get isn't a number.
=> Safer rounding on GroupCard

src/@ui/NativeWebRouter/ProtectedRoute.js, src/settings/index.js
=> Redirect to home page on web logout to prevent endless redirect bug

src/AppRouter.js
=> redirect /signup to /login

src/@data/withGive/selectors/getOrderDetails.js, src/AppRouter.js
=> Sync Alpha to Beta

src/AppRouter.js
=> Sync Beta to Master

src/@data/withGive/resolvers/mutations.js, src/@utils/removeUndefined.js
Added more Sentry logging for more/better information on problems our people are seeing.
=> Add More Sentry

src/@data/withRestoredGive/index.js
- Check for state or userToken before attempting to do something with it
=> Potential Fix for JSON Parse Error

src/@ui/ImagePicker/index.js
=> check for a uri before you try to create an image file (#683)

android/app/src/main/java/host/exp/exponent/generated/DetachBuildConstants.java, app.json, src/@utils/content/share.js
Fixes: [#4440](https://newspring.atlassian.net/browse/SYS-4440)
Fixes the Android share feature, also adding the URL to the clipboard instead of simply the title.
=> Fixes Share Function on Android

android/app/src/main/java/host/exp/exponent/generated/AppConstants.java, ios/newspring/Supporting/EXShell.plist
=> Updated Release Channels

android/app/build.gradle
Fixes [SYS-4545 Android Crashing from Firebase Call](https://newspring.atlassian.net/browse/SYS-4545)
=> Fix Android 6.1.0 Crashing

.github/PULL_REQUEST_TEMPLATE.md, android/app/build.gradle, app-config.js, ios/newspring/Supporting/EXShell.plist, src/@ui/forms/SavedPaymentReviewForm.js
Fixes [[SYS-4545](https://newspring.atlassian.net/browse/SYS-4545)]
Creator
-------
Reviewer
--------
=> Release 6.1.1

android/app/build.gradle, app-config.js, ios/newspring/Supporting/EXShell.plist, ios/newspring/Supporting/Info.plist
Config file changes for the 6.1.2 release
=> Release 6.1.2

src/@ui/forms/PaymentConfirmationForm.js
This allows for the web giving process to know that the gift came from the web.
Creator
-------
Reviewer
--------
=> updated logic to account for web

src/@ui/forms/ContributionForm/index.js
Creator
-------
Reviewer
--------
=> [SYS-4562] Fix Fund Loading

src/@ui/ContributionsChartHero/index.js
Fixes issue not created in JIRA where the ScrollView on the Hero was not filling the container so there would be white space.
=> Fixes ScrollView in Giving Dashboard Hero

src/give/ContributionHistory/ContributionHistoryList.js
=> [SYS-4464] Giving History List Render Fix

android/app/build.gradle, app-config.js, app.json, ios/newspring/Supporting/EXShell.plist, ios/newspring/Supporting/Info.plist
=> Updates Versioning to 6.1.3

android/app/src/main/java/host/exp/exponent/generated/AppConstants.java
=> Update AppConstants with new release channel

package.json
=> Updated package.json to 6.1.3

package.json
This updates the author information in the `package.json`.
=> Updated Author Information

app.json, src/@data/utils/fetchMoreResolver.js
We are having problems across the app in many places with duplicates and skips and when scrolling. This attempts to rewrite the function that handles `fetchMore`. *Extensive* testing will need to be done.
=> (SYS-4582) Fix Scrolling Skips and Duplicates

.github/PULL_REQUEST_TEMPLATE.md, .gitignore, android/app/build.gradle, android/app/src/main/AndroidManifest.xml, android/app/src/main/java/host/exp/exponent/generated/AppConstants.java, android/build.gradle, app-config.js, app.json, ios/newspring/Supporting/EXShell.plist, ios/newspring/Supporting/Info.plist, ios/newspring/newspring.entitlements, package.json, scripts/bump_version.py, src/@data/withTransactions/index.js, src/@ui/ContributionsChartHero/index.js, src/@ui/forms/ContributionForm/FundInput.js, src/@ui/forms/ContributionForm/__snapshots__/ContributionForm.tests.js.snap, src/@ui/forms/ContributionForm/__snapshots__/FundInput.tests.js.snap, src/@ui/forms/PaymentConfirmationForm.js, src/@utils/last4.js, src/AppRouter.js, src/give/ContributionHistory/ContributionHistoryFilter.js, src/give/ContributionHistory/ContributionHistoryList.js
Currently, the short links that work are something like https://rm2y5.goo.gl/XXXXX which is ugly and so comms will never use it. I added the ability for a better-looking link so they’ll actually want to use short links again.
Creator
-------
Reviewer
--------
=> (SYS-4522) Added new domain for short links

android/app/build.gradle, android/app/src/main/java/host/exp/exponent/generated/AppConstants.java, ios/newspring/Supporting/EXShell.plist, ios/newspring/Supporting/Info.plist, package.json
=> release 6.1.4

android/app/src/main/AndroidManifest.xml, ios/newspring/newspring.entitlements, src/AppRouter.js
=> Removed Short Link Code (#755)

src/@data/withGroupFinderResults/groupsQuery.js, src/@data/withGroupInfo/groupQuery.js
=> Fixes GroupFinder Searches

.gitignore, README.md, android/app/src/main/java/host/exp/exponent/generated/AppConstants.java, appcenter-post-clone.sh, src/@data/withGroupFinderResults/groupsQuery.js, src/@data/withGroupInfo/groupQuery.js
=> Alpha -> Beta

src/@data/withGivingStatementDownloadLink/index.js
Fixes [SYS-4615](https://newspring.atlassian.net/secure/RapidBoard.jspa?rapidView=2&projectKey=SYS&modal=detail&selectedIssue=SYS-4615)
=> Fixes PDF Print Button to include contributions on last day of the year

src/@data/withGivingStatementDownloadLink/index.js
=> Alpha to Beta (PDF FIX)

src/@ui/forms/LoginForm.js, src/AppRouter.js
Login form will now redirect to `/give/now` on login.
Bad `/signup/` url will now redirect to `/login`
=> Fix Login Form

src/@ui/forms/LoginForm.js
* fix login form
* removed unneeded route
* removed the specific /signup/ redirect because we fixed the workflow in Rock
=> Fix Login Form (#772)

src/@ui/forms/LoginForm.js
=> Beta -> Master

android/app/src/main/AndroidManifest.xml
https://newspring.atlassian.net/secure/RapidBoard.jspa?rapidView=2&projectKey=SYS&modal=detail&selectedIssue=SYS-4627
=> (SYS-4627) Fixed Two Icons In Drawer

ios/newspring/Supporting/LaunchScreen.xib, ios/newspring/Supporting/main.m
Fixes [SYS-4641](https://newspring.atlassian.net/secure/RapidBoard.jspa?rapidView=2&projectKey=SYS&modal=detail&selectedIssue=SYS-4641)
=> Centers NS logo on IOS launch screen

android/app/build.gradle, android/app/src/main/java/host/exp/exponent/generated/AppConstants.java, ios/newspring/Supporting/EXShell.plist, ios/newspring/Supporting/Info.plist, package.json
This contains a fix for android GroupFinder and centers the iOS splash screen.
Once this is done, we can create Beta PR to test in the stores.
=> Release Version 6.1.5

scripts/bump_version.py, src/settings/index.js
This will allow us to see what version of the Expo bundle is loaded onto the app.
=> (SYS-4647) Adds Version Number to App

src/@ui/Meta/__tests__/__snapshots__/index.js.snap, src/@ui/forms/ContributionForm/FundInput.js, src/@ui/forms/ContributionForm/__snapshots__/ContributionForm.tests.js.snap, src/@ui/forms/ContributionForm/index.js
=> (DEV-3623) Added Pre-selection Prop

android/app/build.gradle, android/app/src/main/java/host/exp/exponent/generated/AppConstants.java, ios/newspring/Supporting/EXShell.plist, ios/newspring/Supporting/Info.plist, package.json, src/settings/index.js
=> Release v6.1.6

android/app/build.gradle, android/app/src/main/java/host/exp/exponent/generated/AppConstants.java, ios/newspring/Supporting/EXShell.plist, ios/newspring/Supporting/Info.plist, package.json, src/settings/index.js
=> Release v6.1.6 (#787)

.gitignore, android/app/build.gradle, android/app/src/main/java/host/exp/exponent/generated/AppConstants.java, ios/newspring/Supporting/EXShell.plist, ios/newspring/Supporting/Info.plist, package.json, src/settings/index.js
=> (DEV-3656) Fixes Crashlytics Android Bug

.gitignore, android/app/build.gradle, android/app/src/main/java/host/exp/exponent/generated/AppConstants.java, ios/newspring/Supporting/EXShell.plist, ios/newspring/Supporting/Info.plist, package.json, src/settings/index.js
* updated fabric lib
* added xcode file to gitignore
* updated to v6.1.7
=> Alpha->Beta

android/app/build.gradle, android/app/src/main/java/host/exp/exponent/generated/AppConstants.java, ios/newspring/Supporting/EXShell.plist, ios/newspring/Supporting/Info.plist, package.json, src/settings/index.js
=> (DEV-3663) Beta -> Master

src/group-finder/GroupSingle.js
Updated Group Leader Toolbox link to point to new page for group rosters.
=> Updated Group Leader Toolbox Link
